services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./
      dockerfile: next.dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - DATABASE_URL=${DATABASE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DUFFEL_TOKEN=${DUFFEL_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - AI_PROVIDER=${AI_PROVIDER}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres -d journeyjolt"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

volumes:
  pgdata:
networks:
  app_network:
    driver: bridge
